### ISSUE TITLE
Представление основных частей в виде docker-контейнеров

### ISSUE THREAD

**Issue by Star-v-ban** [moevm/mse1h2024-clock-cv#13]

**Comment by KristinaImbir** [comment]
Был создан docker файл для каждой из частей приложения, в частности для SQL, backend, frontend. Так же был создан файл  [docker-compose.dev.yml](https://github.com/moevm/mse1h2024-clock-cv/blob/docker-full/deploy/docker-compose.dev.yml), объединяющий создание, сборку и запуск всех частей приложения в виде docker-контейнеров.
