### ISSUE TITLE
Реализация страницы с результатами 

### ISSUE THREAD

**Issue by Star-v-ban** [moevm/mse1h2024-clock-cv#16]

**Comment by Koryakinaisen** [comment]
- Были связаны между собой страницы
- В странице результата был добавлен вывод результата.
- В модальное окно был добавлен вывод результата и описания теста, также реализован запрос картинки на сервер и вывод его на странице
- Модальное окно было переименовано и перемещено в папку /components
- В страницу загрузки была добавлена валидация загружаемого файла, также исправлено скачивание макета.
