### ISSUE TITLE
Объединить серверную и клиентскую часть

### ISSUE THREAD

**Issue by Star-v-ban** [moevm/mse1h2024-clock-cv#24]
Необходимо связать и проверить работу серверной части с клиентской

**Comment by KristinaImbir** [comment]
Был создан файл  [docker-compose.dev.yml](https://github.com/moevm/mse1h2024-clock-cv/blob/docker-full/deploy/docker-compose.dev.yml), объединяющий создание, сборку и запуск всех частей приложения в виде docker-контейнеров.
