### ISSUE TITLE
Презентация и Readme

### ISSUE THREAD

**Issue by Star-v-ban** [moevm/mse1h2024-clock-cv#26]
Реализовать  создание интерфейса для взаимодействия между клиентскими и серверными приложениями, используя принципы и стандарты, определенные в архитектуре REST.

**Comment by KristinaImbir** [comment]
Было прописано 2 запроса к backend. 
- `/upload` - Запрос на загрузку и проверку cv компонентом фотографии
- `/images` - Получение результатов по id фотографии
