### ISSUE TITLE
OpenCV

### ISSUE THREAD

**Issue by Star-v-ban** [moevm/mse1h2024-clock-cv#3]
Изучить OpenCv библиотеку и разобраться в её функционале

**Comment by bleeeana** [comment]
Был изучен основной функционал библиотеки OpenCV: показ изображений, преобразование цветовой модели изображения(например, преобразование модели BGR в GRAY, BGR в RGB и тд.), скрещивание изображений, blurring с помощью различных методов, использование морфологических операторов для обработки краев в бинарном изображении, обнаружение по шаблону с помощью функции matchTemplate и т.д, использование преобразований Хафа для нахождения кругов и прямых линий на изображении. Был получен практический опыт использования функционалом OpenCV.
