### ISSUE TITLE
Изменение извлечения шаблонов чисел и анализ стрелок

### ISSUE THREAD

**Issue by Star-v-ban** [moevm/mse1h2024-clock-cv#44]
Улучшение процесса извлечения  шаблонов чисел и их последующей оценки и добавление описания о исправленных методах

**Comment by Dariiiii** [comment]
Для корректной обработки цвет шаблонной окружности был изменен на синий (чтобы избежать наложения цифр/стрелок на окружность). Добавлена функция удаления окружности с изображения. Добавлены тестовые картинки соответствующие 1-6 баллам.

**Comment by Dariiiii** [comment]
При слишком большом написании цифр, была ошибка в определении двузначного числа (места на часах мало и все цифры находятся рядом). Чтобы исправить эту ошибку была переписана соответствующая функция. Также был исправлен баг некорректного определения окружности (появился в связи с добавлением с функции удаления).

Для усовершенствования распознавания рукописных цифр было принято несколько попыток улучшения кода: 
- так как в рамках нашего проекта мы не используем машинное обучение, этот вариант сразу был отброшен
- применение морфологических операторов так же не привело к улучшению распознавания цифр
- сравнение характеристики нормализованных моментов различных цифр с помощью метрик сходства, таких как евклидово расстояние или косинусное сходство так же не привело к улучшению результата.
В связи с этим было принято решение дополнять нашу базу с шаблонами цифр и не менять текущий код.

**Comment by Dariiiii** [comment]
Чтобы пользователь мог понять, какие из цифр нечитабельные (слишком кривые или написаны не как на шаблоне) для программы, было добавлено подсвечивание этих цифр красным (аналогично подсвечиванию ошибок).

**Comment by bleeeana** [comment]
Были исправлены некоторые ошибки с определением времени на картинке, обработана ситуация, в которой стрелки лежат друг на друге(например, 12:00).
